### ISSUE TITLE
Usage with CF and DT 1.10

### ISSUE THREAD

**Issue by ghost** [YopparaiNeko/Coldfusion-DataTables#1]
Hello:
I've tried to get this started with the CF and DT1.10. I'm calling the ajax routine like:
  "ajax": "DataTables.cfc?method=processCall",
However it returns a 500 Error stating that the Component Datatables.cfc doesn't have a method called processCall.

What am i Missing?

**Comment by YopparaiNeko** [comment]
processCall is not a remote function. The idea is to make an ajax call to a method that invokes processCall. So you'd have `ajax: "DTCalls.cfc?method=fooBar"`. This way you can use fooBar to massage the data and make any pre-processing necessary before invoking the main processCall. Just make sure that the arguments.ci match up with the columns on the jqdt.

**Comment by webdevsourcerer** [comment]
Ah,
I was missing something. :)

**Comment by YopparaiNeko** [comment]
No problem, let me know if that resolved your issue.
