### ISSUE TITLE
TimeStampFormat function is missing

### ISSUE THREAD

**Issue by nikitul** [YopparaiNeko/Coldfusion-DataTables#3]
TimeStampFormat function is missing.
I know is not a big deal, but ...

**Comment by YopparaiNeko** [comment]
I'm a derp derp. Good catch, thanks!

**Comment by nikitul** [comment]
Do not blame yourself :)
It could happen to anyone.

**Comment by nikitul** [comment]
My temporary solution was this:
```html
<cfset tempObj["val"] = "#DateFormat(Arguments.args[k],'yyyy-mm-dd')#T#TimeFormat(Arguments.args[k],'HH:mm:ss')#"> 
```
And is a problem with column search on datetime columns. The return json is not valid because of Executing Database Query Error.
And another problem with a datetime column is in the json result.
Now results are something like this:
"February, 26 1959 00:00:00"
and if I want to format it (dd/mm/yyyy - europe time) with moment.js I've got this warning :
```text
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
```
I will try to find myself a solution, but for now I do not have one.
